In [14]:
from datasets import FrameImageDataset, FrameVideoDataset

image_dataset = FrameImageDataset(
    root_dir="/dtu/datasets1/02516/ucf101_noleakage/"
)
video_dataset = FrameVideoDataset(
    root_dir="/dtu/datasets1/02516/ucf101_noleakage/",
)

In [15]:
import torch
k = 4600
print(image_dataset[k]['input'].shape)
print(image_dataset[k]['target'])


torch.Size([3, 224, 224])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])


In [21]:
import numpy as np
np.unique(image_dataset.df['label'].to_numpy()).shape[0]
image_dataset.df['label'].nunique()
k = 2
torch.nn.functional.one_hot(torch.tensor(k), num_classes=4)

tensor([0, 0, 1, 0])

In [34]:
outputs = torch.randn(2, 5)
outputs = outputs.softmax(dim=-1)
targets = torch.randint(0, 3, (2,))

top_2_acc = (outputs.topk(2, dim=-1).indices == targets.unsqueeze(1)).float().mean()
top_2_acc

tensor(0.5000)

In [28]:
import torch
labels = torch.randint(0, 10, (32,))
output = torch.randn(32, 1)

if output.shape[-1] == 1:
    # binary classification
    print((output > 0.0).long().flatten())

# multi class classification
print(output.argmax(dim=-1))


tensor([1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
        0, 1, 0, 1, 0, 0, 1, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])
